POST http://localhost:3333/musicas
Contente-Type: application/json

{
    "titulo": "Karma",
    "artista": "Taylor Swift",
    "ano_lancamento": 2020,
}

###

GET http://localhost:3333/musicas?search=cardigan 

###

GET http://localhost:3333/musicas

###

PUT  http://localhost:3333/musicas/
Contente-Type: application/json

{
    "titulo": "cardigan",
    "artista": "Taylor Swift",
    "ano_lancamento": 2020,
}

###

DELETE http://localhost:3333/musicas/