//cadastra
POST http://localhost:3333/musica
Content-Type: application/json

{
    "titulo": "Karma",
    "artista": "Taylor Swift",
    "anolancamento": 2020
}

###

//aparece o cadastro
GET http://localhost:3333/musica

###

//pesquisa
GET http://localhost:3333/musica?search=cardigan 

###

//atualizar
PUT  http://localhost:3333/musica/
Content-Type: application/json

{
    "titulo": "cardigan",
    "artista": "Taylor Swift",
    "anolancamento": 2020
}

###

//deleta
DELETE http://localhost:3333/musica/